# Generated by Django 4.2.16 on 2025-02-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgebraCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=255)),
                ('result', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeometryCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=100)),
                ('dimension', models.FloatField()),
                ('result', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
