# Generated by Django 4.2.16 on 2025-02-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_mathentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathentry',
            name='category',
            field=models.CharField(choices=[('algebra', 'Алгебра'), ('geometry', 'Геометрия')], default='tg', max_length=10, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
